syntax = "proto3";
import "google/protobuf/wrappers.proto";
import "fixed_point_dto.proto";

option csharp_namespace = "Ingweland.Fog.Inn.Models.Hoh";

message HeroFinishWaveRequestDto {
  google.protobuf.BytesValue battle_id = 2;
  repeated WaveResultUnitStatDto unit_stats = 3;
  WaveTimelineDto timeline = 4;
  bool used_auto_battle = 6;
  float battle_speed = 7;
  repeated RecordedBattleAction recorded_actions = 8;
  FixedPointDTO last_update_time = 10;
}

message WaveResultUnitStatDto {
  reserved 2;
  string unit_stat = 1;
  repeated WaveResultUnitStatValueDto values = 3;
}

message WaveResultUnitStatValueDto {
  int32 in_battle_id = 1;
  FixedPointDTO value = 2;
}

message WaveTimelineDto {
  repeated WaveTimelineEntryDto entries = 1;
}

message WaveTimelineEntryDto {
  int32 time_milliseconds = 1;
  WaveTimelineAbilityCasterDto ability_caster = 11;
  WaveTimelineAbilityTargetDto ability_target = 12;
}

message WaveTimelineAbilityCasterDto {
  string battle_ability_definition_id = 1;
  int32 timeline_action_id = 2;
  WaveTimelineUnitIdentifierDto caster = 4;
}

message WaveTimelineAbilityTargetDto {
  int32 timeline_action_id = 1;
  WaveTimelineUnitIdentifierDto caster = 7;
  WaveTimelineUnitIdentifierDto target = 8;
  string u1 = 107;
  WaveTimelineAffectedStatDto unit_stat = 112;
  int32 result_value = 115;
}

message WaveTimelineAffectedStatDto {
  string unit_stat = 1;
  float value = 2;
  int32 u1_status = 11;
}

message WaveTimelineUnitIdentifierDto {
  int32 in_battle_id = 1;
}

message RecordedBattleAction {
  message TriggerAbilityForUnit {
    int32 unit_id = 1;
  }
  message SetHeroAutoCast {
    int32 unit_id = 1;
    bool enabled = 2;
  }
  FixedPointDTO time = 4;
  oneof action {
    RecordedBattleAction.TriggerAbilityForUnit trigger_ability_for_unit = 2;
    bool try_toggle_auto_battle = 3;
    RecordedBattleAction.SetHeroAutoCast set_hero_auto_cast = 5;
  }
}